apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-inventory-logs-pvc
  namespace: food-inventory
  labels:
    app: food-inventory
    env: production
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-inventory-data-pvc
  namespace: food-inventory
  labels:
    app: food-inventory
    env: production
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi